namespace SolarMicronet.Web.Services;

/// <summary>
/// ABIs de los contratos inteligentes
/// </summary>
public static class ContractABIs
{
    public const string EnergonTokenABI = @"[
        {""inputs"":[],""name"":""name"",""outputs"":[{""internalType"":""string"",""name"":"""",""type"":""string""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[],""name"":""symbol"",""outputs"":[{""internalType"":""string"",""name"":"""",""type"":""string""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[],""name"":""decimals"",""outputs"":[{""internalType"":""uint8"",""name"":"""",""type"":""uint8""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[],""name"":""totalSupply"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""}],""name"":""balanceOf"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""},{""internalType"":""address"",""name"":"""",""type"":""address""}],""name"":""allowance"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":""to"",""type"":""address""},{""internalType"":""uint256"",""name"":""value"",""type"":""uint256""}],""name"":""transfer"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":""spender"",""type"":""address""},{""internalType"":""uint256"",""name"":""value"",""type"":""uint256""}],""name"":""approve"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":""from"",""type"":""address""},{""internalType"":""address"",""name"":""to"",""type"":""address""},{""internalType"":""uint256"",""name"":""value"",""type"":""uint256""}],""name"":""transferFrom"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""nonpayable"",""type"":""function""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""address"",""name"":""from"",""type"":""address""},{""indexed"":true,""internalType"":""address"",""name"":""to"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""value"",""type"":""uint256""}],""name"":""Transfer"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""address"",""name"":""owner"",""type"":""address""},{""indexed"":true,""internalType"":""address"",""name"":""spender"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""value"",""type"":""uint256""}],""name"":""Approval"",""type"":""event""}
    ]";

    public const string MicrogridManagerABI = @"[
        {""inputs"":[],""name"":""admin"",""outputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""}],""name"":""isRegistered"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""}],""name"":""participantType"",""outputs"":[{""internalType"":""uint8"",""name"":"""",""type"":""uint8""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""}],""name"":""authorizedMeters"",""outputs"":[{""internalType"":""bool"",""name"":"""",""type"":""bool""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":"""",""type"":""address""}],""name"":""meterNonce"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[],""name"":""getCurrentValidators"",""outputs"":[{""internalType"":""address[3]"",""name"":"""",""type"":""address[3]""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[],""name"":""nextActivityId"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[],""name"":""getParticipantCount"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[],""name"":""getFundBalance"",""outputs"":[{""internalType"":""uint256"",""name"":"""",""type"":""uint256""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""}],""name"":""getActivity"",""outputs"":[{""internalType"":""uint256"",""name"":""id"",""type"":""uint256""},{""internalType"":""string"",""name"":""description"",""type"":""string""},{""internalType"":""uint256"",""name"":""reward"",""type"":""uint256""},{""internalType"":""address"",""name"":""executor"",""type"":""address""},{""internalType"":""uint8"",""name"":""state"",""type"":""uint8""},{""internalType"":""address[3]"",""name"":""validatorsSnapshot"",""type"":""address[3]""},{""internalType"":""uint8"",""name"":""approvals"",""type"":""uint8""}],""stateMutability"":""view"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":""participant"",""type"":""address""},{""internalType"":""uint8"",""name"":""pType"",""type"":""uint8""}],""name"":""registerParticipant"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":""meter"",""type"":""address""},{""internalType"":""bool"",""name"":""enabled"",""type"":""bool""}],""name"":""authorizeMeter"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[],""name"":""updateValidators"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":""participant"",""type"":""address""},{""internalType"":""uint256"",""name"":""amount"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""nonce"",""type"":""uint256""},{""internalType"":""bytes"",""name"":""signature"",""type"":""bytes""},{""internalType"":""address"",""name"":""meter"",""type"":""address""}],""name"":""generateEnergy"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""address"",""name"":""participant"",""type"":""address""},{""internalType"":""uint256"",""name"":""amount"",""type"":""uint256""},{""internalType"":""uint256"",""name"":""nonce"",""type"":""uint256""},{""internalType"":""bytes"",""name"":""signature"",""type"":""bytes""},{""internalType"":""address"",""name"":""meter"",""type"":""address""}],""name"":""consumeEnergySigned"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""string"",""name"":""description"",""type"":""string""},{""internalType"":""uint256"",""name"":""reward"",""type"":""uint256""}],""name"":""createActivity"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""}],""name"":""claimActivity"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""}],""name"":""submitActivity"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""}],""name"":""approveActivity"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""}],""name"":""processPayment"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""inputs"":[{""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""}],""name"":""cancelActivity"",""outputs"":[],""stateMutability"":""nonpayable"",""type"":""function""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""address"",""name"":""participant"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""amount"",""type"":""uint256""},{""indexed"":true,""internalType"":""address"",""name"":""meter"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""toParticipant"",""type"":""uint256""},{""indexed"":false,""internalType"":""uint256"",""name"":""toFund"",""type"":""uint256""}],""name"":""EnergyGenerated"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""address"",""name"":""participant"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""amount"",""type"":""uint256""},{""indexed"":true,""internalType"":""address"",""name"":""meter"",""type"":""address""}],""name"":""EnergyConsumed"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""},{""indexed"":false,""internalType"":""string"",""name"":""description"",""type"":""string""},{""indexed"":false,""internalType"":""uint256"",""name"":""reward"",""type"":""uint256""}],""name"":""ActivityCreated"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""},{""indexed"":true,""internalType"":""address"",""name"":""executor"",""type"":""address""}],""name"":""ActivityClaimed"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""},{""indexed"":false,""internalType"":""address[3]"",""name"":""validators"",""type"":""address[3]""}],""name"":""ActivitySubmitted"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""},{""indexed"":true,""internalType"":""address"",""name"":""validator"",""type"":""address""}],""name"":""ActivityApproved"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""},{""indexed"":true,""internalType"":""address"",""name"":""executor"",""type"":""address""},{""indexed"":false,""internalType"":""uint256"",""name"":""reward"",""type"":""uint256""}],""name"":""ActivityPaid"",""type"":""event""},
        {""anonymous"":false,""inputs"":[{""indexed"":true,""internalType"":""uint256"",""name"":""activityId"",""type"":""uint256""}],""name"":""ActivityCancelled"",""type"":""event""}
    ]";
}
